language: php

php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  - DB=mysql

matrix:
  exclude:
    - php: hhvm
      env: DB=mysql  
  allow_failures:
    - php: 7.0
    - php: hhvm

before_script:
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS account;" -uroot; fi
  - composer self-update

