language: php
php:
  - 5.6
  - hhvm
script: phpunit class.login.php
script: phpunit class.logout.php
script: phpunit class.register.php

sudo: false

after_success:
  - bash <(curl -s https://codecov.io/bash)
